services:
  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080" # ホスト:コンテナ
    volumes:
      - .:/app # カレントディレクトリをコンテナにマウント（リアルタイム反映のため）
    environment:
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: go-db
    platform: linux/x86_64 # M1/M2 Mac対策（Windowなら無くても動くが安全のため）
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql # データ永続化

volumes:
  db-data: